services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/faq_db
      - SECRET_KEY=your_secret_key
  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
